### PR TITLE
Whl failed to parse correctly when using pipkin, works correctly when…

### PR DESCRIPTION
**Pull request by surdouski**
… util is patched with this. Also updated requirements.txt with package used.

### CODE REVIEW

**Comment by aivarannamaa** [comment]
Thank you!

What do you think, would it be easy to fix this parsing task without introducing a new dependency? I may want to submit `pipkin` for inclusion in Debian package repo, and any dependency not already present in Debian would be an obstacle for this.

**Comment by surdouski** [comment]
It's a fairly lightweight dependency that would be unlikely to need an update. That being said, I understand the aversion to dependencies, so if you wanted to recreate the functionality of it, you can find it defined [here](https://github.com/jwodder/wheel-filename/blob/master/src/wheel_filename/__init__.py)

**Comment by aivarannamaa** [comment]
Thanks again!

**Comment by surdouski** [comment]
Yw. I should note I did run into this problem again with tarballs, so I think that part of the code needs to be revised a bit. 

I ended up just using upip itself for my project, which works fine in it’s own way, although I think it would be nicer to have some sort of sync-packages-file. My current complaint with using upip is that I can’t subclass anything from packages that need to be upip installed, because the package might not exist yet (before it installs the first time) when loading class definitions.

**Comment by aivarannamaa** [comment]
Can you tell me the names, which were parsed incorrectly?

**Comment by surdouski** [comment]
I would if I still had them, I’m sorry but I didn’t make a note of their names. However, I think a generic regex for tarballs should work.

**Pull request merged**
